/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.SignInController;
import controller.SignUpController;
import dto.User;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author VMQ
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form DangKi
     */
    public SignUp() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }
    
    User user = new User();
    SignUpController signupcontroller = new SignUpController();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbl_TenDangNhap = new javax.swing.JLabel();
        lbl_MatKhau = new javax.swing.JLabel();
        lbl_MatKhau2 = new javax.swing.JLabel();
        lbl_Email = new javax.swing.JLabel();
        lbl_NgaySinh = new javax.swing.JLabel();
        lbl_GioiTinh = new javax.swing.JLabel();
        lbl_DiaChi = new javax.swing.JLabel();
        txt_TenDangNhap = new javax.swing.JTextField();
        ptxt_MatKhau1 = new javax.swing.JPasswordField();
        ptxt_MatKhau2 = new javax.swing.JPasswordField();
        txt_email = new javax.swing.JTextField();
        txt_NgaySinh = new javax.swing.JTextField();
        rbtn_Nam = new javax.swing.JRadioButton();
        rbtn_Nu = new javax.swing.JRadioButton();
        txt_DiaChi = new javax.swing.JTextField();
        btn_XacNhan = new javax.swing.JButton();
        lbl_DangKi = new javax.swing.JLabel();
        btn_TayTrang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        lbl_TenDangNhap.setText("Tên đăng nhập");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 47, 0, 0);
        jPanel1.add(lbl_TenDangNhap, gridBagConstraints);

        lbl_MatKhau.setText("Mật khẩu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 75, 0, 0);
        jPanel1.add(lbl_MatKhau, gridBagConstraints);

        lbl_MatKhau2.setText("Nhập lại mật khẩu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 34, 0, 0);
        jPanel1.add(lbl_MatKhau2, gridBagConstraints);

        lbl_Email.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 95, 0, 0);
        jPanel1.add(lbl_Email, gridBagConstraints);

        lbl_NgaySinh.setText("Ngày sinh");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 72, 0, 0);
        jPanel1.add(lbl_NgaySinh, gridBagConstraints);

        lbl_GioiTinh.setText("Giới tính");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 81, 0, 0);
        jPanel1.add(lbl_GioiTinh, gridBagConstraints);

        lbl_DiaChi.setText("Địa chỉ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 87, 0, 0);
        jPanel1.add(lbl_DiaChi, gridBagConstraints);

        txt_TenDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TenDangNhapActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 98;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 28, 0, 75);
        jPanel1.add(txt_TenDangNhap, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 98;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 28, 0, 75);
        jPanel1.add(ptxt_MatKhau1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 98;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 28, 0, 75);
        jPanel1.add(ptxt_MatKhau2, gridBagConstraints);

        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 98;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 28, 0, 75);
        jPanel1.add(txt_email, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 98;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 28, 0, 75);
        jPanel1.add(txt_NgaySinh, gridBagConstraints);

        buttonGroup1.add(rbtn_Nam);
        rbtn_Nam.setText("Nam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 28, 0, 0);
        jPanel1.add(rbtn_Nam, gridBagConstraints);

        buttonGroup1.add(rbtn_Nu);
        rbtn_Nu.setText("Nữ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 75);
        jPanel1.add(rbtn_Nu, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 98;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 28, 0, 75);
        jPanel1.add(txt_DiaChi, gridBagConstraints);

        btn_XacNhan.setText("Xác nhận");
        btn_XacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XacNhanActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(77, 59, 35, 0);
        jPanel1.add(btn_XacNhan, gridBagConstraints);

        lbl_DangKi.setText("Đăng kí");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 0, 0, 0);
        jPanel1.add(lbl_DangKi, gridBagConstraints);

        btn_TayTrang.setText("Tẩy trắng");
        btn_TayTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TayTrangActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(77, 17, 35, 75);
        jPanel1.add(btn_TayTrang, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_TenDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TenDangNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TenDangNhapActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void btn_TayTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TayTrangActionPerformed
        // TODO add your handling code here:
        txt_TenDangNhap.setText(null);
        txt_NgaySinh.setText(null);
        txt_DiaChi.setText(null);
        txt_email.setText(null);
        ptxt_MatKhau1.setText(null);
        ptxt_MatKhau2.setText(null);
    }//GEN-LAST:event_btn_TayTrangActionPerformed

    private void btn_XacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XacNhanActionPerformed
        // TODO add your handling code here:
        //try {
            if(txt_TenDangNhap.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Tên đăng nhập không được rỗng", "Lỗi", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(txt_email.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Email không được rỗng", "Lỗi", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!ptxt_MatKhau1.getText().equals(ptxt_MatKhau2.getText()))
        {
            JOptionPane.showMessageDialog(null, "Mật khẩu 1 2 phải giống nhau", "Lỗi", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        user.setUserUsername(txt_TenDangNhap.getText());
        if(signupcontroller.checkUserName(user))
        {
            JOptionPane.showMessageDialog(null,"User name đã tồn tại", "Lỗi", JOptionPane.WARNING_MESSAGE);
            return;
        }
        user.setUserID(0);
        user.setUserPassword(ptxt_MatKhau1.getText());
        if(rbtn_Nam.isSelected())
            user.setUserGioitinh("Nam");
        else user.setUserGioitinh("Nu");
        user.setUserEmail(txt_email.getText());
        user.setUserAddress(txt_DiaChi.getText());
        System.out.println(user);
        if(signupcontroller.insertUser(user))
            JOptionPane.showMessageDialog(null, "Tài khoản được khởi tạo", "Thành công", JOptionPane.WARNING_MESSAGE);
        else
            JOptionPane.showMessageDialog(null, "Thất bại", "Lỗi", JOptionPane.WARNING_MESSAGE);
        //} catch (Exception e) {
          //  e.getStackTrace();
        //}
        
    }//GEN-LAST:event_btn_XacNhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_TayTrang;
    private javax.swing.JButton btn_XacNhan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_DangKi;
    private javax.swing.JLabel lbl_DiaChi;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_GioiTinh;
    private javax.swing.JLabel lbl_MatKhau;
    private javax.swing.JLabel lbl_MatKhau2;
    private javax.swing.JLabel lbl_NgaySinh;
    private javax.swing.JLabel lbl_TenDangNhap;
    private javax.swing.JPasswordField ptxt_MatKhau1;
    private javax.swing.JPasswordField ptxt_MatKhau2;
    private javax.swing.JRadioButton rbtn_Nam;
    private javax.swing.JRadioButton rbtn_Nu;
    private javax.swing.JTextField txt_DiaChi;
    private javax.swing.JTextField txt_NgaySinh;
    private javax.swing.JTextField txt_TenDangNhap;
    private javax.swing.JTextField txt_email;
    // End of variables declaration//GEN-END:variables
}
