/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AuthorController;
import controller.GenresController;
import controller.SingerController;
import controller.SongController;
import controller.UserController;
import dto.*;
import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JComponent.TOOL_TIP_TEXT_KEY;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.sql.Date;
import javax.swing.JFrame;

/**
 *
 * @author VMQ
 */
public class UploadSong extends javax.swing.JFrame {

    /**
     * Creates new form testUp
     */
    
    ///////////// còn update lên host
    
    Song song = new Song();
    Singer singer = new Singer();
    Author author = new Author();
    Genres genres = new Genres();
    SingerController singerController = new SingerController();
    AuthorController authorController = new AuthorController();
    GenresController genresController = new GenresController();
    SongController songController = new SongController();
    
    private static UploadSong ins;
    private static int singerid;
    private static int authorid;
    private static int genresid=1;
    private static String Songaddress;
    private static File Songfile;
    
    public static UploadSong getInstane(){
        return ins;
    }

    public UploadSong() {
        initComponents();
        singerController.setModelTable(tbl_Singer);
        authorController.setModelTable(tbl_Author);
        genresController.setModelComboBox(cbb_Genre);
        ins = this;
        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }
    
    
    public void toTxtSinger(int row){
        txt_SingerName.setText(tbl_Singer.getValueAt(row, 0).toString());
        txt_Singer_Birth.setText(tbl_Singer.getValueAt(row, 1).toString());
        txta_Singer_Note.setText(tbl_Singer.getValueAt(row, 2).toString());
    }
    
    public void toTxtAuthor(int row){
        txt_AuthorName.setText(tbl_Author.getValueAt(row, 0).toString());
        txt_Au_Birth.setText(tbl_Author.getValueAt(row, 1).toString());
    }
    
    public void setGenresID(int gid){
        genresid=gid;
        System.out.println("genresid ="+genresid);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pn_Song = new javax.swing.JPanel();
        lbl_Title = new javax.swing.JLabel();
        btn_Upload = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txt_SongName = new javax.swing.JTextField();
        lbl_Name = new javax.swing.JLabel();
        lbl_Singer = new javax.swing.JLabel();
        lbl_Author = new javax.swing.JLabel();
        lbl_Address = new javax.swing.JLabel();
        txt_SongAddress = new javax.swing.JTextField();
        txt_SongSinger = new javax.swing.JTextField();
        txt_SongAuthor = new javax.swing.JTextField();
        lbl_Genre = new javax.swing.JLabel();
        lbl_Lyrics = new javax.swing.JLabel();
        cbb_Genre = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_SongLyrics = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        btn_file = new javax.swing.JButton();
        pn_Singer = new javax.swing.JPanel();
        lbl_Title1 = new javax.swing.JLabel();
        pn_Singer_Info = new javax.swing.JPanel();
        lbl_Name1 = new javax.swing.JLabel();
        txt_SingerName = new javax.swing.JTextField();
        lbl_Singer_Birth = new javax.swing.JLabel();
        txt_Singer_Birth = new javax.swing.JTextField();
        lbl_Note = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txta_Singer_Note = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Singer = new javax.swing.JTable();
        pn_Singer_Button = new javax.swing.JPanel();
        btn_Insert = new javax.swing.JButton();
        btn_Clear = new javax.swing.JButton();
        btn_Choose = new javax.swing.JButton();
        pn_Author = new javax.swing.JPanel();
        pn_Author_Button = new javax.swing.JPanel();
        btn_Insert1 = new javax.swing.JButton();
        btn_Clear1 = new javax.swing.JButton();
        btn_Choose1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_Author = new javax.swing.JTable();
        pn_Author_Info = new javax.swing.JPanel();
        lbl_Name2 = new javax.swing.JLabel();
        txt_AuthorName = new javax.swing.JTextField();
        lbl_Au_Birth = new javax.swing.JLabel();
        txt_Au_Birth = new javax.swing.JTextField();
        lbl_Title2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_Title.setText("Upload bài hát");

        btn_Upload.setText("Upload");
        btn_Upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UploadActionPerformed(evt);
            }
        });

        lbl_Name.setText("Tên bài hát");

        lbl_Singer.setText("Ca sĩ");

        lbl_Author.setText("Nhạc sĩ");

        lbl_Address.setText("Địa chỉ");

        lbl_Genre.setText("Thể loại");

        lbl_Lyrics.setText("Lời bài hát");

        cbb_Genre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txta_SongLyrics.setColumns(20);
        txta_SongLyrics.setRows(5);
        jScrollPane1.setViewportView(txta_SongLyrics);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Lyrics)
                    .addComponent(lbl_Genre)
                    .addComponent(lbl_Author)
                    .addComponent(lbl_Singer)
                    .addComponent(lbl_Address))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbb_Genre, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1)
                    .addComponent(txt_SongSinger)
                    .addComponent(txt_SongAuthor)
                    .addComponent(txt_SongAddress)
                    .addComponent(txt_SongName))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbl_Name)
                    .addContainerGap(305, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_SongName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_SongAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Address))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_SongSinger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Singer))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_SongAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Author))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbb_Genre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Genre))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lbl_Lyrics)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbl_Name)
                    .addContainerGap(314, Short.MAX_VALUE)))
        );

        btn_file.setText("Chọn file");
        btn_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 156, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(btn_file, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(60, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 73, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(btn_file)
                    .addContainerGap(45, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout pn_SongLayout = new javax.swing.GroupLayout(pn_Song);
        pn_Song.setLayout(pn_SongLayout);
        pn_SongLayout.setHorizontalGroup(
            pn_SongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_SongLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(pn_SongLayout.createSequentialGroup()
                .addGroup(pn_SongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_SongLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(lbl_Title))
                    .addGroup(pn_SongLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(btn_Upload, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_SongLayout.setVerticalGroup(
            pn_SongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_SongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Title)
                .addGroup(pn_SongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_SongLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_SongLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btn_Upload)
                .addGap(73, 73, 73))
        );

        jTabbedPane1.addTab("Upload", pn_Song);

        lbl_Title1.setText("Quản lí ca sĩ");

        lbl_Name1.setText("Tên ca sĩ");

        lbl_Singer_Birth.setText("Ngày sinh");

        lbl_Note.setText("Ghi chú");

        txta_Singer_Note.setColumns(20);
        txta_Singer_Note.setRows(5);
        jScrollPane4.setViewportView(txta_Singer_Note);

        javax.swing.GroupLayout pn_Singer_InfoLayout = new javax.swing.GroupLayout(pn_Singer_Info);
        pn_Singer_Info.setLayout(pn_Singer_InfoLayout);
        pn_Singer_InfoLayout.setHorizontalGroup(
            pn_Singer_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_Singer_InfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_Singer_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pn_Singer_InfoLayout.createSequentialGroup()
                        .addComponent(lbl_Name1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_SingerName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_Singer_InfoLayout.createSequentialGroup()
                        .addComponent(lbl_Singer_Birth)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addGroup(pn_Singer_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Singer_Birth, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(pn_Singer_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_Singer_InfoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbl_Note)
                    .addContainerGap(313, Short.MAX_VALUE)))
        );
        pn_Singer_InfoLayout.setVerticalGroup(
            pn_Singer_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_Singer_InfoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pn_Singer_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_SingerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Name1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(pn_Singer_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Singer_Birth)
                    .addComponent(txt_Singer_Birth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pn_Singer_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_Singer_InfoLayout.createSequentialGroup()
                    .addContainerGap(152, Short.MAX_VALUE)
                    .addComponent(lbl_Note)
                    .addGap(52, 52, 52)))
        );

        tbl_Singer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_Singer);

        btn_Insert.setText("Thêm");
        btn_Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InsertActionPerformed(evt);
            }
        });

        btn_Clear.setText("Tẩy trắng");
        btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearActionPerformed(evt);
            }
        });

        btn_Choose.setText("Chọn");
        btn_Choose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChooseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_Singer_ButtonLayout = new javax.swing.GroupLayout(pn_Singer_Button);
        pn_Singer_Button.setLayout(pn_Singer_ButtonLayout);
        pn_Singer_ButtonLayout.setHorizontalGroup(
            pn_Singer_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_Singer_ButtonLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pn_Singer_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_Choose, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Insert, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        pn_Singer_ButtonLayout.setVerticalGroup(
            pn_Singer_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_Singer_ButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Clear)
                .addGap(35, 35, 35)
                .addComponent(btn_Insert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btn_Choose)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout pn_SingerLayout = new javax.swing.GroupLayout(pn_Singer);
        pn_Singer.setLayout(pn_SingerLayout);
        pn_SingerLayout.setHorizontalGroup(
            pn_SingerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_SingerLayout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(pn_SingerLayout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(lbl_Title1)
                .addGap(203, 281, Short.MAX_VALUE))
            .addGroup(pn_SingerLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(pn_Singer_Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(pn_Singer_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        pn_SingerLayout.setVerticalGroup(
            pn_SingerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_SingerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Title1)
                .addGroup(pn_SingerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_SingerLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(pn_Singer_Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(pn_SingerLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(pn_Singer_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Ca sĩ", pn_Singer);

        btn_Insert1.setText("Thêm");
        btn_Insert1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Insert1ActionPerformed(evt);
            }
        });

        btn_Clear1.setText("Tẩy trắng");
        btn_Clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Clear1ActionPerformed(evt);
            }
        });

        btn_Choose1.setText("Chọn");
        btn_Choose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Choose1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_Author_ButtonLayout = new javax.swing.GroupLayout(pn_Author_Button);
        pn_Author_Button.setLayout(pn_Author_ButtonLayout);
        pn_Author_ButtonLayout.setHorizontalGroup(
            pn_Author_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_Author_ButtonLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pn_Author_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_Choose1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Insert1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Clear1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        pn_Author_ButtonLayout.setVerticalGroup(
            pn_Author_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_Author_ButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Clear1)
                .addGap(35, 35, 35)
                .addComponent(btn_Insert1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btn_Choose1)
                .addGap(29, 29, 29))
        );

        tbl_Author.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbl_Author);

        lbl_Name2.setText("Tên nhạc sĩ");

        lbl_Au_Birth.setText("Ngày sinh");

        javax.swing.GroupLayout pn_Author_InfoLayout = new javax.swing.GroupLayout(pn_Author_Info);
        pn_Author_Info.setLayout(pn_Author_InfoLayout);
        pn_Author_InfoLayout.setHorizontalGroup(
            pn_Author_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_Author_InfoLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(pn_Author_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_AuthorName, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Au_Birth, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(pn_Author_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_Author_InfoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pn_Author_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_Au_Birth)
                        .addComponent(lbl_Name2))
                    .addContainerGap(240, Short.MAX_VALUE)))
        );
        pn_Author_InfoLayout.setVerticalGroup(
            pn_Author_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_Author_InfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_AuthorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_Au_Birth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
            .addGroup(pn_Author_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_Author_InfoLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_Name2)
                    .addGap(47, 47, 47)
                    .addComponent(lbl_Au_Birth)
                    .addGap(117, 117, 117)))
        );

        lbl_Title2.setText("Quản lí nhạc sĩ");

        javax.swing.GroupLayout pn_AuthorLayout = new javax.swing.GroupLayout(pn_Author);
        pn_Author.setLayout(pn_AuthorLayout);
        pn_AuthorLayout.setHorizontalGroup(
            pn_AuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_AuthorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(pn_AuthorLayout.createSequentialGroup()
                .addGroup(pn_AuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pn_AuthorLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(pn_Author_Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_AuthorLayout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(lbl_Title2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(pn_Author_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        pn_AuthorLayout.setVerticalGroup(
            pn_AuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_AuthorLayout.createSequentialGroup()
                .addGroup(pn_AuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_AuthorLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(pn_Author_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_AuthorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_Title2)
                        .addGap(19, 19, 19)
                        .addComponent(pn_Author_Info, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Nhạc sĩ", pn_Author);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_UploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UploadActionPerformed
        
        song.setAuthorID(authorid);
        song.setGenresID(genresid);
        song.setSongCountListen(1);
        song.setSongDateUpLoad(null);
        song.setSongID(0);
        song.setSongName(txt_SongName.getText());
        song.setSong_lyrics(txta_SongLyrics.getText());        
        song.setSong_singer(singerid);
        song.setSongNote(null);
        song.setUserID(UserController.userIns.getUserID());
        /////// upload nhac lay dia chi
        song.setSongsrc(Songaddress);
        
        System.out.println(song);
        if(songController.insertDataToSong(song))
            JOptionPane.showMessageDialog(null, "Upload bài hát thành công", "Thành công", JOptionPane.WARNING_MESSAGE);
        else
            JOptionPane.showMessageDialog(null, "Không upload được", "Lỗi", JOptionPane.WARNING_MESSAGE);
        
    }//GEN-LAST:event_btn_UploadActionPerformed

    private void btn_InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InsertActionPerformed
        singer.setSingerID(0);
        singer.setSingerEmail(null);
        singer.setSingerBirthday(txt_Singer_Birth.getText());
        singer.setSingerNote(txta_Singer_Note.getText());    
        singer.setSingerName(txt_SingerName.getText());
        singer.setSingerAddress(null);
        
        if(singerController.InsertSinger(singer))
            JOptionPane.showMessageDialog(null, "Thêm ca sĩ thành công", "Thành công", JOptionPane.WARNING_MESSAGE);
        else
            JOptionPane.showMessageDialog(null, "Không thêm được", "Lỗi", JOptionPane.WARNING_MESSAGE);
        
        singerController.resetSingerTable();
        
    }//GEN-LAST:event_btn_InsertActionPerformed

    private void btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearActionPerformed
        txta_Singer_Note .setText(null);
        txt_SingerName.setText(null);
        txt_Singer_Birth.setText(null);
    }//GEN-LAST:event_btn_ClearActionPerformed

    private void btn_ChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChooseActionPerformed
        txt_SongSinger.setText(txt_SingerName.getText());
        singerid=singerController.chosenid;
        System.out.println("chosen singer id "+singerid);   
        
    }//GEN-LAST:event_btn_ChooseActionPerformed

    private void btn_Insert1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Insert1ActionPerformed
        author.setAuthorAddress("");
        author.setAuthorBirthday(txt_Au_Birth.getText());
        author.setAuthorEmail("");
        author.setAuthorID(0);
        author.setAuthorName(txt_AuthorName.getText());
        if(authorController.InsertAuthor(author))
            JOptionPane.showMessageDialog(null, "Thêm nhạc sĩ thành công", "Thành công", JOptionPane.WARNING_MESSAGE);
        else
            JOptionPane.showMessageDialog(null, "Không thêm được", "Lỗi", JOptionPane.WARNING_MESSAGE);
        authorController.resetAuthorTable();
    }//GEN-LAST:event_btn_Insert1ActionPerformed

    private void btn_Clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Clear1ActionPerformed
        txt_Au_Birth.setText(null);
        txt_AuthorName.setText(null);
    }//GEN-LAST:event_btn_Clear1ActionPerformed

    private void btn_Choose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Choose1ActionPerformed
        txt_SongAuthor.setText(txt_AuthorName.getText());
        authorid= authorController.chosenid;
        System.out.println("chosen author id "+authorid);  
    }//GEN-LAST:event_btn_Choose1ActionPerformed

    private void btn_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fileActionPerformed
        JFileChooser jfc=new JFileChooser();
        jfc.showOpenDialog(null);
        Songfile=jfc.getSelectedFile();
        Songaddress=jfc.getSelectedFile().getAbsolutePath();
        txt_SongAddress.setText(Songaddress);
        System.out.println(Songaddress);
        //jfc.showSaveDialog(null);

    }//GEN-LAST:event_btn_fileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UploadSong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UploadSong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UploadSong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UploadSong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UploadSong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Choose;
    private javax.swing.JButton btn_Choose1;
    private javax.swing.JButton btn_Clear;
    private javax.swing.JButton btn_Clear1;
    private javax.swing.JButton btn_Insert;
    private javax.swing.JButton btn_Insert1;
    private javax.swing.JButton btn_Upload;
    private javax.swing.JButton btn_file;
    private javax.swing.JComboBox cbb_Genre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_Address;
    private javax.swing.JLabel lbl_Au_Birth;
    private javax.swing.JLabel lbl_Author;
    private javax.swing.JLabel lbl_Genre;
    private javax.swing.JLabel lbl_Lyrics;
    private javax.swing.JLabel lbl_Name;
    private javax.swing.JLabel lbl_Name1;
    private javax.swing.JLabel lbl_Name2;
    private javax.swing.JLabel lbl_Note;
    private javax.swing.JLabel lbl_Singer;
    private javax.swing.JLabel lbl_Singer_Birth;
    private javax.swing.JLabel lbl_Title;
    private javax.swing.JLabel lbl_Title1;
    private javax.swing.JLabel lbl_Title2;
    private javax.swing.JPanel pn_Author;
    private javax.swing.JPanel pn_Author_Button;
    private javax.swing.JPanel pn_Author_Info;
    private javax.swing.JPanel pn_Singer;
    private javax.swing.JPanel pn_Singer_Button;
    private javax.swing.JPanel pn_Singer_Info;
    private javax.swing.JPanel pn_Song;
    private javax.swing.JTable tbl_Author;
    private javax.swing.JTable tbl_Singer;
    private javax.swing.JTextField txt_Au_Birth;
    private javax.swing.JTextField txt_AuthorName;
    private javax.swing.JTextField txt_SingerName;
    private javax.swing.JTextField txt_Singer_Birth;
    private javax.swing.JTextField txt_SongAddress;
    private javax.swing.JTextField txt_SongAuthor;
    private javax.swing.JTextField txt_SongName;
    private javax.swing.JTextField txt_SongSinger;
    private javax.swing.JTextArea txta_Singer_Note;
    private javax.swing.JTextArea txta_SongLyrics;
    // End of variables declaration//GEN-END:variables
}
